language: node_js
node_js:
- 6.6

before_install: psql -c 'create database travi_api;' -U postgres

addons:
  postgresql: "9.4"

services: postgresql

env: DATABASE_URL=postgresql://postgres:@localhost/travi_api

install: npm install

sudo: false

after_script: npm run report-coverage

deploy:
  provider: heroku
  api_key:
    secure: ejE97ISrl0D/NeX7mjY+HYaRgEPNtvv6GHWxCXqHiBf+/qTlv9vlOXIUz1ERIqWVC2OZOqDhXYBxFHADWrqXI6VzbX8R23UkosJgMTCpQCN362B5ytpuQynNzAY5TFgt3QNWLJAr9R2/Dzi3IfC89MmUEISJrYzWaiBzr8K1/JU=
  on:
    node: 6.6
