language: node_js
sudo: false
addons:
  postgresql: '9.4'
services: postgresql
notifications:
  email: false
before_install: psql -c 'create database travi_api;' -U postgres
after_script: npm run report-coverage
deploy:
  provider: heroku
  app: travi-api
  api_key:
    secure: U1Z3ODxIt7MA9AWIXj7I2BUyPujDAp8ZmfbHBEDyKIMNwjUWPe7kVu/s+/h801YAfwPHjMo0c5GTI8pShpw+dnZkYnV3pToDNfpgJ1OU+PtraLh1ZZFSEeIndFGJXpI6XPhF8IGiR9acEpj80gu3Ny2hcMIA7WOopcoxefP0idYrH7zTFR3bx6jUByU+1ELQz+so7LSsWpbi8O061vQ7NLCdJDMzHCwmTZUtIt4WUG0WrL84OA7xcF/skRwDIpilQ83H6E4xs+Yo8CPL9yXDJl58V6INKbCbMMaeLJZ2bVRvULp9HC57g83QIBXyGAc5bqYvVwCY92BUPUYuhHtuHGZFzV6pejagzeq2CD1JquQ2IKeUHlVc8FJGplh+IVS59J4LhZes9GIYzlubpbUgLnC/YOBF9mOy3PZaFrCfOPCSn4jzO21HMGXw6iLcsULhEmGFlEbKNVU0dk2SQXPUK2YOn3XnUeb0aq2mMRXjWRyK+HC4dc65lOWEl4N33txy9dPaJdAKLHWrJ0wC3rJISz//vO/pjW2vfR7ohhtNA08EJFsQ+wTucAq3dHOh4/eysqTXVooYzzD1Fv8dIhmz7sEZjqEl8ttpNMMekx4pz+unIcpy99wSOFKJounBvuTi5zyRAIQQcoGRAl++d0NVwG34FBWFHSUrX13GKwmIFbg=
env:
  global:
  - TMPDIR=/tmp/
  - DATABASE_URL=postgresql://postgres:@localhost/travi_api
  - secure: ALW7Z79pKklCNsrxBk/U73zxOl3dOJ7tuJe3DYkkHEu2H1ce2WItRyx1z6xRK2Z25Xm2RmXLLS3Fzp2O5ZtHjdWqevXbUTqrhuZPReTDZOlqTEcvz71rZp8V5srp7jZB+WvZc+vDuuOfk/kJMSXr+hduXzHM52QA95RfVFm/ShE=
  - secure: Ep6FxUJ58oNxPknZOTWFI17W/2PgDy9V512N1RizCBmk1z8uza/5Jv0s5F7iMDL8JPjvtSadKiwpRq+kJwFY2lGU8xczvrCYZAfq+4+HejlDYABw8359V3RuKhh1L2jmGNv1NaNeup2ceHc2ImWnJ6G4pokrY6QpOf6qcJCUDNY=
  - secure: h35ln4QUYZwIxjhIR3Yo0fmULHzzOYgxcwUZWyJubhKvn8VJQzSYcXp1eSRyjLi31XDoLw8IOWre5tqJfpxdcFdWd4oEPWNMy1MMgGH0n8SllfsMjwEHFhbdUYUwa3bMLB7Rgk20zwXhT+U9lPat3WJkD/tnHMicFxQHmpJwmlU=
