language: node_js
sudo: false
addons:
  postgresql: '9.4'
services: postgresql
notifications:
  email: false
before_install: psql -c 'create database travi_api;' -U postgres
after_script: npm run report-coverage
deploy:
  provider: heroku
  app: travi-api
  api_key:
    secure: wtFgjqtSaZ9tKCbEx2MVIww2uvQYVGg9I9ES8NfX29+dd2SQ5tyqIs5TcPpj3Vk/dpKH+ASzanThoiuR2pOiRMbn/3O1gD3+9YZN/FV4oJ4jc7JQrR552LfTnj+s3z/aRwBTDH7jUBBP2WZvtbVm+G/pOOpscyVM8HASWzvPzzCcL1owNgiFv6PZWw5esRXwE3aoaEpN0S1W3T3aB6YoRcY3VKEhkuk1huIKWZY7C/TmX8rSqqqIm3V3zDfo6AD9t+Abe4rlXOBn3I2q5Fbu9i9HPaYRX+w7FRgo4Pv0qFbLPFSL0tLKJ7hPZFr0dZOkky7MjYPx8PHTLwtfj71tenDNcQ4EXWbnQ/NBSTMV7zwK5P5WI7CH5Z9sQ6xHansEC6B9XlFj1yAXDGqxtjH80U6UVssFtKfsx03b1dcAdf9mVR4IR1WTScBvz/TJ7ekDnNwzNXm9ShEMQ8skx/sivCXOzt3w/JDpc3ClTWLlIj6I4fiCkT8ikXFPIGtu3XqlQ6f6/QnaVw6pum8Ihlojud3v65i3zPayEWJDXyHj+/CJevZbV83V+4sdtfTNI4ZJAceNW2M1j8ezD6Xgo9xO4mzLyzpFhrUtRqnSeMVQSXd8cdwn5XVeK7P3BZWVNCFOvTrYqR9TNXlbnnWNvXwYTxd1r2YJ1+HuehYzyb2Fr6o=
env:
  global:
  - TMPDIR=/tmp/
  - DATABASE_URL=postgresql://postgres:@localhost/travi_api
  - secure: ALW7Z79pKklCNsrxBk/U73zxOl3dOJ7tuJe3DYkkHEu2H1ce2WItRyx1z6xRK2Z25Xm2RmXLLS3Fzp2O5ZtHjdWqevXbUTqrhuZPReTDZOlqTEcvz71rZp8V5srp7jZB+WvZc+vDuuOfk/kJMSXr+hduXzHM52QA95RfVFm/ShE=
  - secure: Ep6FxUJ58oNxPknZOTWFI17W/2PgDy9V512N1RizCBmk1z8uza/5Jv0s5F7iMDL8JPjvtSadKiwpRq+kJwFY2lGU8xczvrCYZAfq+4+HejlDYABw8359V3RuKhh1L2jmGNv1NaNeup2ceHc2ImWnJ6G4pokrY6QpOf6qcJCUDNY=
  - secure: h35ln4QUYZwIxjhIR3Yo0fmULHzzOYgxcwUZWyJubhKvn8VJQzSYcXp1eSRyjLi31XDoLw8IOWre5tqJfpxdcFdWd4oEPWNMy1MMgGH0n8SllfsMjwEHFhbdUYUwa3bMLB7Rgk20zwXhT+U9lPat3WJkD/tnHMicFxQHmpJwmlU=
